*** Settings ***
Documentation    Todos os objetos da página Home do sistema

*** Variables ***
&{pg_Home}
...    title=nopCommerce demo store
...    logo_nopCommerce=div[class="header-logo"]
...    btn_register=a[class="ico-register"]
...    btn_login=a[class="ico-login"]
...    my_account=a[class="ico-account"]
...    input_search=input[id="small-searchterms"]
...    btn_search=button[class="button-1 search-box-button"]
