*** Variables ***
&{pg_Pesquisa}
...    title=nopCommerce demo store. Search
...    list_products=div[class="products-container"]
...    option_product=//a[text()="Digital Storm VANQUISH 3 Custom Performance PC"]
...    btn_add_car=//div[@class="product-item" and @data-productid="2"]
...    btn_addToCar=button[id="add-to-cart-button-2"]
...    message=p[class="content"]
...    link_shopping=//a[text()="shopping cart"]